# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author: Alla Isakova
title: AllaIPhoto
email: isakovaaphoto@gmail.com
timezone: "America/Los_Angeles"
permalink: /:categories/:title
facebook: allaiphoto
instagram: allaiphoto
description: >- # this means to ignore newlines until "baseurl:"
  Hi, my name is Alla.
  I enjoy creating pictures that make people happy. So if you live in San Francisco and Bay Area or just traveling, we can capture the great moments of your and your family life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://allaiphoto.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
livereload: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - vendor
  - Gemfile
  - Gemfile.lock
  - bin
  - README.md
